services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: orders
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  order:
    build:
      context: ./order
      dockerfile: Dockerfile
      args:
        TAG: $TAG
        GOARCH: arm64  # Simplified since we're only building for arm64
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: orders
    working_dir: /app
    command: ["sh", "-c", "go test -v ./..."]
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./order:/app

  payment:
    build:
      context: ./payment
      dockerfile: Dockerfile
      args:
        TAG: $TAG
        GOARCH: arm64  # Simplified since we're only building for arm64
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: payments
    working_dir: /app
    command: ["sh", "-c", "go test -v ./..."]
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./payment:/app
