env:
  GO111MODULE: "on"
  GOFLAGS: "-mod=mod"
  CGO_ENABLED: "0"

steps:
  # Build all services
  - label: ":docker: Build Services"
    command: |
      echo "--- Building services"
      docker-compose -f docker-compose.ci.yml build

  # Test Order Service
  - label: ":go: Test Order Service"
    command: |
      echo "--- Testing Order Service"
      docker-compose -f docker-compose.ci.yml run --rm order \
        go test -v -coverprofile=coverage.out ./...
      
      # Upload coverage report
      buildkite-agent artifact upload "**/coverage.out"

  # Test Payment Service
  - label: ":go: Test Payment Service"
    command: |
      echo "--- Testing Payment Service"
      docker-compose -f docker-compose.ci.yml run --rm payment \
        go test -v -coverprofile=coverage.out ./...
      
      # Upload coverage report
      buildkite-agent artifact upload "**/coverage.out"

  # Login to Docker Hub and push images
  - label: ":docker: Push to Docker Hub"
    if: build.branch == 'main'  # Only push on main branch
    command: |
      echo "--- Logging into Docker Hub"
      echo "$DOCKER_PASSWORD" | docker login -u "hackermonk" --password-stdin
      
      echo "--- Tagging and pushing images"
      docker tag buildkite-secure-pipeline-order hackermonk/order:${BUILDKITE_COMMIT:0:7}
      docker tag buildkite-secure-pipeline-payment hackermonk/payment:${BUILDKITE_COMMIT:0:7}
      
      echo "--- Pushing images to Docker Hub"
      docker push hackermonk/order:${BUILDKITE_COMMIT:0:7}
      docker push hackermonk/payment:${BUILDKITE_COMMIT:0:7}
      
      # Also tag as latest for the most recent successful build
      docker tag buildkite-secure-pipeline-order hackermonk/order:latest
      docker tag buildkite-secure-pipeline-payment hackermonk/payment:latest
      docker push hackermonk/order:latest
      docker push hackermonk/payment:latest

  # Deploy to local Kubernetes
  - label: ":kubernetes: Deploy to Local K8s"
    if: build.branch == 'main'  # Only deploy on main branch
    command: |
      echo "--- Deploying to local Kubernetes"
      
      # Set image names with Docker Hub username
      export ORDER_IMAGE=hackermonk/order:${BUILDKITE_COMMIT:0:7}
      export PAYMENT_IMAGE=hackermonk/payment:${BUILDKITE_COMMIT:0:7}
      
      echo "--- Using images:"
      echo "Order: $ORDER_IMAGE"
      echo "Payment: $PAYMENT_IMAGE"
      
      # Apply Kubernetes manifests with envsubst to replace image names
      echo "--- Applying Kubernetes manifests"
      envsubst < kubernetes/order-deployment.yaml | kubectl apply -f -
      envsubst < kubernetes/payment-deployment.yaml | kubectl apply -f -
      kubectl apply -f kubernetes/mysql-deployment.yaml
      kubectl apply -f kubernetes/services.yaml
      
      echo "--- Deployment status"
      kubectl get pods -n default
      
      echo "--- Services"
      kubectl get svc -n default
