env:
  GO111MODULE: "on"
  GOFLAGS: "-mod=mod"
  CGO_ENABLED: "0"

steps:
  - label: ":wrench: Tooling & Context"
    command: .buildkite/steps/01_prep.sh

  - label: ":docker: Build (compose tests' images)"
    command: .buildkite/steps/02_compose_build.sh

  - label: ":go: Test Services"
    command: .buildkite/steps/03_tests.sh

  - label: ":package: Build k8s images for Minikube"
    command: .buildkite/steps/04_build_images.sh

  - label: ":minikube: Load images into cluster"
    command: .buildkite/steps/05_minikube_load.sh

  - label: ":kubernetes: Deploy (no registry)"
    command: .buildkite/steps/06_deploy.sh
