steps:
  - key: setup
    label: ":wrench: Setup"
    command: ".buildkite/steps/01_setup.sh"

  - key: tools
    label: ":hammer_and_wrench: Install scan tools"
    depends_on: setup
    command: ".buildkite/steps/09_install_tools.sh"

  # -------- Pre-build gates --------
  - key: gitleaks
    label: ":lock: Secrets Scan (Gitleaks)"
    depends_on: setup
    command: ".buildkite/steps/04_secret_scanning.sh"
    artifact_paths:
      - "artifacts/gitleaks.sarif"
    soft_fail: true  

  - key: semgrep
    label: ":mag_right: SAST Scan (Semgrep)"
    depends_on: setup
    command: ".buildkite/steps/05_sast.sh"
    artifact_paths:
      - "artifacts/semgrep.json"
    soft_fail: true  

  - key: sca
    label: ":shield: SCA Scan (govulncheck + Trivy)"
    depends_on: setup
    command: ".buildkite/steps/06_sca.sh"
    soft_fail: true           # start soft; flip to hard-fail later
    artifact_paths:
      - "artifacts/govulncheck.txt"
      - "artifacts/trivy-fs.sarif"
    soft_fail: true  

  # -------- Build --------
  - key: build
    label: ":package: Build Containers"
    depends_on:
      - setup
      - gitleaks
      - semgrep
      - sca
    command: ".buildkite/steps/02_build.sh"

  # -------- Post-build security --------
  - key: trivy_img
    label: ":microscope: Container Scan (Trivy)"
    depends_on: build
    command: ".buildkite/steps/07_image_scanning.sh"
    soft_fail: true           # start soft; flip to hard-fail later
    artifact_paths:
      - "artifacts/trivy-order.sarif"
      - "artifacts/trivy-payment.sarif"

  - key: sbom
    label: ":page_facing_up: SBOM + Image Signing (Syft + Cosign)"
    depends_on: build
    command: ".buildkite/steps/08_sbom_sign.sh"
    artifact_paths:
      - "artifacts/sbom-*.spdx.json"
      - "artifacts/sbom-*.sig"
      - "artifacts/cosign.*"
    soft_fail: true  

  # -------- Deploy --------
  - key: deploy
    label: ":kubernetes: Deploy to Minikube on MacOS"
    depends_on:
      - build
      - trivy_img
      - sbom
    command: ".buildkite/steps/03_deploy.sh"
