env:
  GO111MODULE: "on"
  GOFLAGS: "-mod=mod"
  CGO_ENABLED: "0"

steps:
  # Build all services
  - label: ":docker: Build Services"
    command: |
      echo "--- Building services"
      docker-compose -f docker-compose.ci.yml build

  # Test Order Service
  - label: ":go: Test Order Service"
    command: |
      echo "--- Testing Order Service"
      docker-compose -f docker-compose.ci.yml run --rm order \
        go test -v -coverprofile=coverage.out ./...
      
      # Upload coverage report
      buildkite-agent artifact upload "**/coverage.out"

  # Test Payment Service
  - label: ":go: Test Payment Service"
    command: |
      echo "--- Testing Payment Service"
      docker-compose -f docker-compose.ci.yml run --rm payment \
        go test -v -coverprofile=coverage.out ./...
      
      # Upload coverage report
      buildkite-agent artifact upload "**/coverage.out"

  # Integration Test (Optional)
  - label: ":test_tube: Integration Tests"
    command: |
      echo "--- Starting services"
      docker-compose -f docker-compose.ci.yml up -d
      
      echo "--- Running integration tests"
      # Add your integration test commands here
      # Example: docker-compose -f docker-compose.ci.yml run test go test ./e2e/...
      
      echo "--- Service status"
      docker-compose -f docker-compose.ci.yml ps
