steps:
  - key: "setup"
    label: ":wrench: Setup"
    command: ".buildkite/steps/01_setup.sh"

  - label: ":package: Build images"
    depends_on: "setup"
    command: ".buildkite/steps/02_build.sh"

  - label: ":kubernetes: Deploy to Minikube"
    depends_on: "setup"
    command: ".buildkite/steps/03_deploy.sh"
