env:
  GO111MODULE: "on"
  GOFLAGS: "-mod=mod"
  CGO_ENABLED: "0"

steps:
  # Build all services
  - label: ":docker: Build Services"
    command: |
      echo "--- Building services"
      docker-compose -f docker-compose.ci.yml build

  # Test Services
  - label: ":go: Test Services"
    command: |
      echo "--- Building test environment"
      # Build the images first without running them
      docker-compose -f docker-compose.ci.yml build
      
      # Start only MySQL
      echo "--- Starting MySQL"
      docker-compose -f docker-compose.ci.yml up -d mysql
      
      echo "--- Waiting for MySQL to be ready"
      sleep 30
      
      echo "--- Running Order Service tests"
      # Run tests directly in the container without volume mounts
      docker run --rm --network container:buildkite-secure-pipeline-mysql-1 \
        -e DB_HOST=localhost \
        -e DB_PORT=3306 \
        -e DB_USER=user \
        -e DB_PASSWORD=password \
        -e DB_NAME=orders \
        buildkite-secure-pipeline-order \
        sh -c "cd /app && go test -v ./..."
      
      echo "--- Running Payment Service tests"
      docker run --rm --network container:buildkite-secure-pipeline-mysql-1 \
        -e DB_HOST=localhost \
        -e DB_PORT=3306 \
        -e DB_USER=user \
        -e DB_PASSWORD=password \
        -e DB_NAME=payments \
        buildkite-secure-pipeline-payment \
        sh -c "cd /app && go test -v ./..."
      
      echo "--- Cleaning up"
      docker-compose -f docker-compose.ci.yml down -v

  # Login to Docker Hub and push images
  - label: ":docker: Push to Docker Hub"
    if: build.branch == 'main'  # Only push on main branch
    command: |
      echo "--- Logging into Docker Hub"
      # Using environment variable for token
      echo "$DOCKERHUB_TOKEN" | docker login -u "hackermonk" --password-stdin
      
      echo "--- Tagging and pushing images"
      docker tag buildkite-secure-pipeline-order hackermonk/order:${BUILDKITE_COMMIT:0:7}
      docker tag buildkite-secure-pipeline-payment hackermonk/payment:${BUILDKITE_COMMIT:0:7}
      
      echo "--- Pushing images to Docker Hub"
      docker push hackermonk/order:${BUILDKITE_COMMIT:0:7}
      docker push hackermonk/payment:${BUILDKITE_COMMIT:0:7}
      
      # Also tag as latest for the most recent successful build
      docker tag buildkite-secure-pipeline-order hackermonk/order:latest
      docker tag buildkite-secure-pipeline-payment hackermonk/payment:latest
      docker push hackermonk/order:latest
      docker push hackermonk/payment:latest

  # Deploy to local Kubernetes
  - label: ":kubernetes: Deploy to Local K8s"
    if: build.branch == 'main'  # Only deploy on main branch
    command: |
      echo "--- Installing required tools"
      apt-get update && apt-get install -y gettext-base
      
      echo "--- Deploying to local Kubernetes"
      
      # Set image names with Docker Hub username
      export ORDER_IMAGE=hackermonk/order:${BUILDKITE_COMMIT:0:7}
      export PAYMENT_IMAGE=hackermonk/payment:${BUILDKITE_COMMIT:0:7}
      
      echo "--- Using images:"
      echo "Order: $ORDER_IMAGE"
      echo "Payment: $PAYMENT_IMAGE"
      
      # Apply Kubernetes manifests with envsubst to replace image names
      echo "--- Applying Kubernetes manifests"
      # Change to kubernetes directory and get full path
      cd kubernetes
      KUBE_DIR=$(pwd)
      
      # Process and apply each manifest
      for manifest in order-deployment.yaml payment-deployment.yaml mysql-deployment.yaml services.yaml; do
        if [ -f "$manifest" ]; then
          echo "Processing $manifest..."
          envsubst < "$manifest" | kubectl apply -f - || echo "Failed to apply $manifest"
        else
          echo "Warning: $manifest not found"
        fi
      done
      
      echo "--- Deployment status"
      kubectl get pods -A
      
      echo "--- Services"
      kubectl get svc -A
