env:
  GO111MODULE: "on"
  GOFLAGS: "-mod=mod"
  CGO_ENABLED: "0"

steps:
  # Simple build and test
  - label: ":docker: Build and Test"
    command: |
      echo "--- Building services"
      docker-compose -f docker-compose.ci.yml build
      
      echo "--- Running tests"
      docker-compose -f docker-compose.ci.yml up -d
      docker-compose -f docker-compose.ci.yml ps
      
      # Add your test commands here
      # Example: docker-compose -f docker-compose.ci.yml run order go test ./...
    
  # Optional: Add deployment steps later
  # - label: ":rocket: Deploy (Example)"
  #   command: echo "Deployment would happen here"
  #   if: build.branch == 'main'
