apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: payment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: ${PAYMENT_IMAGE}          # replaced by envsubst
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: DATA_SOURCE_URL
              value: "user:password@tcp(mysql.mysql.svc.cluster.local:3306)/payments?charset=utf8mb4&parseTime=True&loc=Local"
            - name: PORT
              value: "8081"
            - name: GRPC_PORT
              value: "8081"
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
