apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql
  labels: { app: mysql }
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  selector: { app: mysql }
---
apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: order
  labels: { app: order }
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector: { app: order }
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: payment
  labels: { app: payment }
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
  selector: { app: payment }
